[phases.setup]
nixPkgs = ["nodejs_22", "pnpm-9_x"]

[phases.install]
cmds = ["cd my-app && pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["cd my-app && pnpm build"]

[start]
cmd = "cd my-app && pnpm start"
